
spring:
  banner:
    location: banner.txt
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://ec2-54-225-203-79.compute-1.amazonaws.com:5432/daccopj6pvqr7b
    username: scjrgerduehcip
    password: 8f79ebf3ae76954157e44b23e2291ea4fe361a2ece0786ed8b0639397547ea9e
  data:
    cassandra:
      schema-action: create_if_not_exists
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        enable_lazy_load_no_trans: true
        dialect: org.hibernate.dialect.PostgreSQL92Dialect